spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:22409/railway
spring.datasource.username=postgres
spring.datasource.password=gCwBSXAUmgsWwwVFRSJzeStOpOwaDjha
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
